# fly.toml app configuration file generated for cfes-backend-aged-star-4108 on 2025-08-01T22:48:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cfes-backend-aged-star-4108'
primary_region = 'bog'

[build]

[[mounts]]
  source = 'wwebjs_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
